python-wand: add SRCREV, fix QA issue and add comment about imagemagick version
* use SRCREV instead of tag name, so that bitbake doesn't translate tag to SRCREV
  every time it's parsing this recipe
* fix QA issue:
  ERROR: QA Issue: python-wand: Files/directories were installed but not shipped in any package:
    /usr/share
    /usr/share/README.rst
* add comment about imagemagick version needed to use python-wand-native
  otherwise it will use imagemagick from host

Change-Id: Ie0fd3549d31e48a0f5d3a5083f4fc90854d5d25c
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit e487ca4b1590c1104b7a3b20f7bf343a2861b0fc)