linux-linaro-aarch64: use ;nobranch=1
Due to rebasing the tagged commits get dropped from the branch leading to:

WARNING: Failed to fetch URL git://git.linaro.org/git/kernel/linux-linaro-tracking.git;protocol=http;branch=linux-linaro;name=kernel, attempting MIRRORS if available
ERROR: Fetcher failure: Unable to find revision e72caa28875ec600a6d1bb3e11813fd21c4adb16 in branch linux-linaro even from upstream
ERROR: Function failed: Fetcher failure for URL: 'git://git.linaro.org/git/kernel/linux-linaro-tracking.git;protocol=http;branch=linux-linaro;name=kernel'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /build/scratch/angstrom-v2014.12/build/tmp-angstrom_next-eglibc/work/genericarmv8-angstrom-linux/linux-linaro-aarch64/3.15+gitAUTOINC+e72caa2887-r0/temp/log.do_fetch.22052
ERROR: Task 4 (/build/scratch/angstrom-v2014.12/sources/meta-linaro/meta-linaro/recipes-kernel/linux/linux-linaro-aarch64.bb, do_fetch) failed with exit code '1'

Use the 'nobranch' parameter as a workaround.

Change-Id: Idb16376cd642c92b42ed4cc9cd1ea4ff039d4ffb
Signed-off-by: Koen Kooi <koen.kooi@linaro.org>